version: "3.6"
services:
  # java:
  #   container_name: java
  #   build: ./java
  #   depends_on:
  #     - mysql
  #   ports:
  #     - "8080:8080"
  #   tty: true
  #   volumes:
  #     - ../../backend:/srv:cached
  #   working_dir: /app
  node:
    container_name: node
    build: ./node
    ports:
      - 3000:3000
    volumes:
      - ../../frontend:/usr/src/app:cached
    # command: sh -c "npm install; npm start"
    stdin_open: true
    tty: true
  mysql:
    container_name: mysql
    build: ./mysql
    ports:
      - 3306:3306
    volumes:
      - ../data/mysql:/var/lib/mysql
      - ./mysql/initdb.d/:/docker-entrypoint-initdb.d
  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - "../data/redis:/data"
