version: "3.6"
services:
  api:
    tty: true
    depends_on:
      - mysql
    build:
      context: ../../api/
      dockerfile: Dockerfile
    ports:
      - 8000:3000
    volumes:
      - ../../api:/app
    # command: rails server -b 0.0.0.0
  node:
    container_name: node
    build:
      context: ../../frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../../frontend:/usr/src/app:cached
    command: sh -c "npm install; npm start"
    stdin_open: true
    tty: true
  mysql:
    container_name: mysql
    build: ./mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-db:/var/lib/mysql
      # - ./mysql/initdb.d/:/docker-entrypoint-initdb.d
  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - "../data/redis:/data"
volumes:
  mysql-db:
    driver: local
